'use client'

// src/app/dashboard/staff/_components/DailyReportModal.tsx
// Extracted from StaffDashboardClient.tsx — no logic changes.

import { useState, useEffect } from 'react'
import { getDailyReportAction } from '@/app/actions/receptionist'
import { Modal, fmt12, todayStr, STATUS_CONFIG, type OrgProp, type ApptStatus } from './utils'

export function DailyReportModal({ org, onClose }: { org: OrgProp; onClose: () => void }) {
  const [date, setDate] = useState(todayStr())
  const [data, setData] = useState<any[]>([])
  const [loading, setLoading] = useState(false)

  async function load(d: string) {
    setLoading(true)
    const r = await getDailyReportAction(org.id, d)
    setData(r.data ?? [])
    setLoading(false)
  }

  useEffect(() => { load(date) }, [date])

  const total = data.reduce((s, a) => s + (a.doctor_organizations?.consultation_fee ?? 0), 0)
  const completed = data.filter(a => a.status === 'COMPLETED').length
  const booked = data.filter(a => a.status === 'BOOKED').length
  const walkIns = data.filter(a => a.source === 'WALK_IN').length

  function printReport() {
    const rows = data
      .map(a => `<tr>
        <td>${a.patients?.users?.full_name ?? ''}</td>
        <td>${a.doctor_organizations?.doctors?.full_name ?? ''}</td>
        <td>${fmt12(a.slot_start)}</td>
        <td>${a.source}</td>
        <td>${a.status}</td>
        <td>₹${a.doctor_organizations?.consultation_fee ?? 0}</td>
      </tr>`)
      .join('')

    const w = window.open('', '_blank', 'width=700,height=800')
    if (!w) return
    w.document.write(`
      <html><head><title>Daily Report – ${date}</title>
      <style>
        body { font-family: sans-serif; padding: 20px; font-size: 12px; }
        h1 { font-size: 16px; } h2 { font-size: 13px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th { background: #f3f4f6; padding: 6px 8px; text-align: left; font-size: 11px; }
        td { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; }
        .summary { display: flex; gap: 20px; margin: 12px 0; }
        .stat { background: #f9fafb; padding: 8px 12px; border-radius: 8px; }
        .stat-num { font-size: 20px; font-weight: 700; }
        .stat-label { font-size: 10px; color: #888; }
      </style></head><body>
      <h1>${org.name} — Daily Report</h1>
      <h2>${date}</h2>
      <div class="summary">
        <div class="stat"><div class="stat-num">${data.length}</div><div class="stat-label">Total</div></div>
        <div class="stat"><div class="stat-num">${completed}</div><div class="stat-label">Completed</div></div>
        <div class="stat"><div class="stat-num">${walkIns}</div><div class="stat-label">Walk-ins</div></div>
        <div class="stat"><div class="stat-num">₹${total}</div><div class="stat-label">Revenue</div></div>
      </div>
      <table>
        <tr><th>Patient</th><th>Doctor</th><th>Slot</th><th>Source</th><th>Status</th><th>Fee</th></tr>
        ${rows}
      </table>
      <br/><div style="font-size:10px;color:#999">Generated by YESOPD · ${new Date().toLocaleString()}</div>
      <script>window.print(); window.close();</script>
      </body></html>
    `)
    w.document.close()
  }

  return (
    <Modal title="Daily Report" onClose={onClose}>
      <div className="space-y-4">
        <div className="flex items-center gap-3">
          <input
            type="date"
            value={date}
            onChange={e => setDate(e.target.value)}
            className="text-sm border border-gray-200 rounded-xl px-3 py-2.5 bg-white focus:border-[#006EFF] focus:outline-none flex-1"
          />
          <button
            onClick={printReport}
            className="flex items-center gap-1.5 text-sm font-medium text-[#006EFF] bg-blue-50 px-4 py-2.5 rounded-xl hover:bg-blue-100 transition"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print
          </button>
        </div>

        {!loading && (
          <div className="grid grid-cols-2 gap-3">
            {[
              { label: 'Total',     value: data.length, color: 'text-gray-700' },
              { label: 'Completed', value: completed,   color: 'text-green-600' },
              { label: 'Booked',    value: booked,      color: 'text-blue-600' },
              { label: 'Walk-ins',  value: walkIns,     color: 'text-amber-600' },
            ].map(s => (
              <div key={s.label} className="bg-white rounded-xl border border-gray-100 p-3 text-center">
                <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
                <p className="text-xs text-gray-400 mt-0.5">{s.label}</p>
              </div>
            ))}
          </div>
        )}

        {!loading && (
          <div className="bg-green-50 rounded-xl px-4 py-3 flex items-center justify-between">
            <span className="text-sm font-medium text-green-700">Est. Revenue</span>
            <span className="text-xl font-bold text-green-700">₹{total.toLocaleString('en-IN')}</span>
          </div>
        )}

        {loading && (
          <div className="space-y-2">
            {[1, 2, 3].map(i => (
              <div key={i} className="bg-white rounded-xl h-14 animate-pulse" />
            ))}
          </div>
        )}

        {!loading && data.map(a => {
          const cfg = STATUS_CONFIG[a.status as ApptStatus] ?? STATUS_CONFIG.BOOKED
          return (
            <div key={a.id} className="bg-white rounded-xl border border-gray-100 px-4 py-3 flex items-center gap-3">
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-[#1A1A2E] truncate">{a.patients?.users?.full_name}</p>
                <p className="text-xs text-gray-400">{fmt12(a.slot_start)} · {a.doctor_organizations?.doctors?.full_name}</p>
              </div>
              <div className="text-right shrink-0">
                <span className={`text-xs px-2 py-0.5 rounded-full ${cfg.bg} ${cfg.text}`}>{cfg.label}</span>
                <p className="text-xs text-gray-500 mt-1">₹{a.doctor_organizations?.consultation_fee ?? 0}</p>
              </div>
            </div>
          )
        })}

        {!loading && data.length === 0 && (
          <div className="text-center py-8 text-sm text-gray-400">No appointments for this date.</div>
        )}
      </div>
    </Modal>
  )
}